# Generated by Django 4.0.3 on 2022-05-20 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_comment_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(default=None, max_length=255)),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coffeeshop')),
            ],
        ),
    ]
