# Generated by Django 4.0.3 on 2022-10-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_owners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owners',
        ),
    ]
