# Generated by Django 4.0.3 on 2022-10-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='is_Owner',
            field=models.CharField(max_length=255),
        ),
    ]
