# Generated by Django 4.0.3 on 2022-10-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_owners_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='numRates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
