# Generated by Django 4.0.3 on 2022-11-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField(default=0)),
                ('username', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
