# Generated by Django 4.0.3 on 2022-11-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='shop_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
