# Generated by Django 4.0.3 on 2022-11-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_coffeeshop_hasowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default=None, max_length=255)),
                ('owner_name', models.CharField(default=None, max_length=255)),
                ('position', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
