# Generated by Django 4.0.3 on 2022-11-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='OwnerName',
            field=models.CharField(default='no', max_length=255),
        ),
    ]
