# Generated by Django 4.0.3 on 2022-11-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_coffeeshop_ownername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='shop_name',
        ),
    ]
