# Generated by Django 4.0.3 on 2022-11-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_menu_shop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default=None, max_length=255)),
                ('time', models.CharField(default=None, max_length=255)),
                ('username', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
