# Generated by Django 4.0.3 on 2022-11-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='owner_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
